spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:${user.home}/tmp/h2db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  data:
    neo4j:
      uri: bolt://neo4j:password@localhost
logging:
  level:
    jp.co: DEBUG